name: Make Release

on:
  push:
    tags: 
      - v*.*.*
  
jobs:
        
  Release-Linux:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Publish Linux-x64-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --no-self-contained --runtime linux-x64 --framework net5.0 -o ./build/linux-x64-without-runtime
    - name: Publish Linux-x64
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --self-contained true --runtime linux-x64 --framework net5.0 -o ./build/linux-x64
    - name: Publish Linux-arm-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --no-self-contained --runtime linux-arm --framework net5.0 -o ./build/linux-arm-without-runtime
    - name: Publish Linux-arm
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --self-contained true --runtime linux-arm --framework net5.0 -o ./build/linux-arm
    - name: Publish Linux-arm64-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --no-self-contained --runtime linux-arm64 --framework net5.0 -o ./build/linux-arm64-without-runtime
    - name: Publish Linux-arm64
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --self-contained true --runtime linux-arm64 --framework net5.0 -o ./build/linux-arm64
      
    - name: Pack Linux-x64-without-runtime
      run: tar -czvf linux-x64-without-runtime.tar.gz  -C ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build linux-x64-without-runtime
    - name: Pack Linux-x64
      run: tar -czvf linux-x64.tar.gz  -C ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build linux-x64
    - name: Pack Linux-arm-without-runtime
      run: tar -czvf linux-arm-without-runtime.tar.gz  -C ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build linux-arm-without-runtime
    - name: Pack Linux-arm
      run: tar -czvf linux-arm.tar.gz  -C ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build linux-arm
    - name: Pack Linux-arm64-without-runtime
      run: tar -czvf linux-arm64-without-runtime.tar.gz  -C ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build linux-arm64-without-runtime
    - name: Pack Linux-arm64
      run: tar -czvf linux-arm64.tar.gz  -C ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build linux-arm64
        
    - name: Upload release files
      uses: softprops/action-gh-release@v1
      with: 
        files: |
          linux-x64-without-runtime.tar.gz
          linux-x64.tar.gz
          linux-arm-without-runtime.tar.gz
          linux-arm.tar.gz
          linux-arm64-without-runtime.tar.gz
          linux-arm64.tar.gz
        token: ${{ secrets.RELEASE_TOKEN }}
        
        
        
  Release-Windows: 
  
    runs-on: windows-latest
    
    steps: 
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Publish Win-x64-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --no-self-contained --runtime win-x64 --framework net5.0 -o ./build/win-x64-without-runtime
    - name: Publish Win-x64
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --self-contained true --runtime win-x64 --framework net5.0 -o ./build/win-x64
    - name: Publish Win-x86-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --no-self-contained --runtime win-x86 --framework net5.0 -o ./build/win-x86-without-runtime
    - name: Publish Win-x86
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --self-contained true --runtime win-x86 --framework net5.0 -o ./build/win-x86
    - name: Publish Win-arm-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --no-self-contained --runtime win-arm --framework net5.0 -o ./build/win-arm-without-runtime
    - name: Publish Win-arm
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --self-contained true --runtime win-arm --framework net5.0 -o ./build/win-arm
    - name: Publish Win10-x64-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --no-self-contained --runtime win10-x64 --framework net5.0 -o ./build/win10-x64-without-runtime
    - name: Publish Win10-x64
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --self-contained true --runtime win10-x64 --framework net5.0 -o ./build/win10-x64
    - name: Publish Win10-arm64-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --no-self-contained --runtime win10-arm64 --framework net5.0 -o ./build/win10-arm64-without-runtime
    - name: Publish Win10-arm64
      run: dotnet publish -p:PublishReadyToRun=true --configuration Release --self-contained true --runtime win10-arm64 --framework net5.0 -o ./build/win10-arm64
    
    - name: Pack Win-x64-without-runtime
      run: 7z a win-x64-without-runtime.7z D:\a\MorePracticeMalodyServer\MorePracticeMalodyServer\build\win-x64-without-runtime\
    - name: Pack Win-x64
      run: 7z a win-x64.7z D:\a\MorePracticeMalodyServer\MorePracticeMalodyServer\build\win-x64\
    - name: Pack Win-x86-without-runtime
      run: 7z a win-x86-without-runtime.7z D:\a\MorePracticeMalodyServer\MorePracticeMalodyServer\build\win-x86-without-runtime\
    - name: Pack Win-x86
      run: 7z a win-x86.7z D:\a\MorePracticeMalodyServer\MorePracticeMalodyServer\build\win-x86\
    - name: Pack Win-arm-without-runtime
      run: 7z a win-arm-without-runtime.7z D:\a\MorePracticeMalodyServer\MorePracticeMalodyServer\build\win-arm-without-runtime\
    - name: Pack Win-arm
      run: 7z a win-arm.7z D:\a\MorePracticeMalodyServer\MorePracticeMalodyServer\build\win-arm\
    - name: Pack Win10-x64-without-runtime
      run: 7z a win10-x64-without-runtime.7z D:\a\MorePracticeMalodyServer\MorePracticeMalodyServer\build\win10-x64-without-runtime\
    - name: Pack Win10-x64
      run: 7z a win10-x64.7z D:\a\MorePracticeMalodyServer\MorePracticeMalodyServer\build\win10-x64\
    - name: Pack Win10-arm64-without-runtime
      run: 7z a win10-arm64-without-runtime.7z D:\a\MorePracticeMalodyServer\MorePracticeMalodyServer\build\win10-arm64-without-runtime\
    - name: Pack Win10-arm64
      run: 7z a win10-arm64.7z D:\a\MorePracticeMalodyServer\MorePracticeMalodyServer\build\win10-arm64\
      
    - name: Changelog
      uses: glennawatson/ChangeLog@v1
      id: changelog
          
    - name: Upload release files
      uses: softprops/action-gh-release@v1
      with: 
        body: |
          ${{ steps.Changelog.outputs.changelog }}
        files: |
          win-x64-without-runtime.7z
          win-x64.7z
          win-x86-without-runtime.7z
          win-x86.7z
          win10-x64-without-runtime.7z
          win10-x64.7z
          win10-arm64-without-runtime.7z
          win10-arm64.7z
        token: ${{ secrets.RELEASE_TOKEN }}
        
