name: Make Release

on:
  push:
    branches: 
      - master
    tags: 
      - v*.*.*
  
jobs:
        
  Release Linux:
  
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Publish Linux-x64-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --no-self-contained --runtime linux-x64 --framework net5.0 -o ./build/linux-x64-without-runtime
    - name: Publish Linux-x64
      run: dotnet publish -p:PublishReadyToRun=true --self-contained true --runtime linux-x64 --framework net5.0 -o ./build/linux-x64
    - name: Publish Linux-arm-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --no-self-contained --runtime linux-arm --framework net5.0 -o ./build/linux-arm-without-runtime
    - name: Publish Linux-arm
      run: dotnet publish -p:PublishReadyToRun=true --self-contained true --runtime linux-arm --framework net5.0 -o ./build/linux-arm
    - name: Publish Linux-arm64-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --no-self-contained --runtime linux-arm64 --framework net5.0 -o ./build/linux-arm64-without-runtime
    - name: Publish Linux-arm64
      run: dotnet publish -p:PublishReadyToRun=true --self-contained true --runtime linux-arm64 --framework net5.0 -o ./build/linux-arm64
      
    - name: Pack Linux-x64-without-runtime
      run: tar -czvf linux-x64-without-runtime.tar.gz  -C ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build linux-x64-without-runtime
    - name: Pack Linux-x64
      run: tar -czvf linux-x64.tar.gz  -C ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build linux-x64
    - name: Pack Linux-arm-without-runtime
      run: tar -czvf linux-arm-without-runtime.tar.gz  -C ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build linux-arm-without-runtime
    - name: Pack Linux-arm
      run: tar -czvf linux-arm.tar.gz  -C ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build linux-arm
    - name: Pack Linux-arm64-without-runtime
      run: tar -czvf linux-arm64-without-runtime.tar.gz  -C ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build linux-arm64-without-runtime
    - name: Pack Linux-arm64
      run: tar -czvf linux-arm64.tar.gz  -C ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build linux-arm64
        
    - name: Upload release files
      uses: softprops/action-gh-release@v1
      with: 
        files: |
          linux-x64-without-runtime.tar.gz
          linux-x64.tar.gz
          linux-arm-without-runtime.tar.gz
          linux-arm.tar.gz
          linux-arm64-without-runtime.tar.gz
          linux-arm64.tar.gz
        token: ${{ GITHUB.RELEASE_TOKEN }}
        
        
        
  Release Windows: 
  
    runs-on: windows-latest
    
    steps: 
    
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Publish Win-x64-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --no-self-contained --runtime win-x64 --framework net5.0 -o ./build/win-x64-without-runtime
    - name: Publish Win-x64
      run: dotnet publish -p:PublishReadyToRun=true --self-contained true --runtime win-x64 --framework net5.0 -o ./build/win-x64
    - name: Publish Win-x86-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --no-self-contained --runtime win-x86 --framework net5.0 -o ./build/win-x86-without-runtime
    - name: Publish Win-x86
      run: dotnet publish -p:PublishReadyToRun=true --self-contained true --runtime win-x86 --framework net5.0 -o ./build/win-x86
    - name: Publish Win-arm-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --no-self-contained --runtime win-arm --framework net5.0 -o ./build/win-arm-without-runtime
    - name: Publish Win-arm
      run: dotnet publish -p:PublishReadyToRun=true --self-contained true --runtime win-arm --framework net5.0 -o ./build/win-arm
    - name: Publish Win10-x64-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --no-self-contained --runtime win10-x64 --framework net5.0 -o ./build/win10-x64-without-runtime
    - name: Publish Win10-x64
      run: dotnet publish -p:PublishReadyToRun=true --self-contained true --runtime win10-x64 --framework net5.0 -o ./build/win10-x64
    - name: Publish Win10-arm64-without-runtime
      run: dotnet publish -p:PublishReadyToRun=true --no-self-contained --runtime win10-arm64 --framework net5.0 -o ./build/win10-arm64-without-runtime
    - name: Publish Win10-arm64
      run: dotnet publish -p:PublishReadyToRun=true --self-contained true --runtime win10-arm64 --framework net5.0 -o ./build/win10-arm64
    
    - name: Pack Win-x64-without-runtime
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r win-x64-without-runtime.zip win-x64-without-runtime
        working-directory: ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build
    - name: Pack Win-x64
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r win-x64.zip win-x64
        working-directory: ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build
    - name: Pack Win-x86-without-runtime
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r win-x86-without-runtime.zip win-x86-without-runtime
        working-directory: ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build
    - name: Pack Win-x86
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r win-x86.zip win-x86
        working-directory: ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build
    - name: Pack Win-arm-without-runtime
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r win-arm-without-runtime.zip win-x64-without-runtime
        working-directory: ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build
    - name: Pack Win-arm
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r win-arm.zip win-arm
        working-directory: ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build
    - name: Pack Win10-x64-without-runtime
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r win10-x64-without-runtime.zip win10-x64-without-runtime
        working-directory: ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build
    - name: Pack Win10-x64
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r win10-x64.zip win10-x64
        working-directory: ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build
    - name: Pack Win10-x86-without-runtime
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r win10-x86-without-runtime.zip win10-x86-without-runtime
        working-directory: ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build
    - name: Pack Win10-x86
      uses: montudor/action-zip@v1
      with:
        args: zip -qq -r win10-x86.zip win10-x86
        working-directory: ~/work/MorePracticeMalodyServer/MorePracticeMalodyServer/build
          
    - name: Upload release files
      uses: softprops/action-gh-release@v1
      with: 
        files: |
          linux-x64-without-runtime.tar.gz
          linux-x64.tar.gz
          linux-arm-without-runtime.tar.gz
          linux-arm.tar.gz
          linux-arm64-without-runtime.tar.gz
          linux-arm64.tar.gz
          win-x64-without-runtime.zip
          win-x64.zip
          win-x86-without-runtime.zip
          win-x86.zip
          win10-x64-without-runtime.zip
          win10-x64.zip
          win10-x86-without-runtime.zip
          win10-x86.zip
        token: ${{ GITHUB.RELEASE_TOKEN }}
